version: "3.8"

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/28

volumes:
  static_contents:
  certs:
  mysql_data:

services:
  logger:
    build: ./fluent
    ports:
      - "127.0.0.1:24224:24224"
    volumes:
      - /srv/docker/mount/cms/log/:/fluentd/log/
    environment:
      - TZ=Asia/Tokyo

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cms
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: system
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql/
      - /srv/docker/mount/cms/mysql/backup/:/srv/backup/data/
    healthcheck:
      test: mysqladmin ping -u system -padmin7278
      timeout: 10s
      retries: 10
    logging:
      driver: "fluentd"
      options:
        tag: "mysql"
    networks:
      net:
        aliases:
          - mysql
    depends_on:
       - logger

  php:
    build:
      context: ./php
      args:
        - APP_DOMAIN=${APP_DOMAIN}
        - APP_GIT_URL=${APP_GIT_URL}
    environment:
      TZ: Asia/Tokyo
    volumes:
      - static_contents:/var/www/app/public/
    logging:
      driver: "fluentd"
      options:
        tag: "php"
    networks:
      net:
        aliases:
          - php
    depends_on:
      mysql:
        condition: service_healthy

  # certbot for first time build
  certbot:
    build: ./certbot
    volumes:
      - static_contents:/var/www/html/
      - certs:/etc/letsencrypt/
    command: >
      certonly --standalone -n --keep --agree-tos
      -d ${APP_DOMAIN}
      -w /var/www/html/
      -m st6.048153@gmail.com

  web:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - static_contents:/usr/share/nginx/html/
      - certs:/etc/nginx/ssl/
    logging:
      driver: "fluentd"
      options:
        tag: "nginx"
    networks:
      net:
        aliases:
          - web
    depends_on:
      - logger
      - certbot

  # certbot for update cert
  certbot-renew:
    build: ./certbot
    volumes:
      - static_contents:/var/www/html/
      - certs:/etc/letsencrypt/
    command: >
      certonly --webroot -n --keep --agree-tos
      -d ${APP_DOMAIN}
      -w /var/www/html/
      -m st6.048153@gmail.com
